### PR TITLE
V1 plugins file types service layer

### PR DESCRIPTION
**Pull request by pscemama-mitre**

### CODE REVIEW

**Comment by pscemama-mitre** [comment]
@keithmanville @jkglasbrenner two things.

1) See [this note](https://github.com/usnistgov/dioptra/blob/820c61a4cdcac091b55ee126fbfdb8752e9de761/src/dioptra/restapi/v1/plugins/service.py#L870-L874) about modifying a plugin file


2) There is a linting error arising from [here](https://github.com/usnistgov/dioptra/blob/820c61a4cdcac091b55ee126fbfdb8752e9de761/src/dioptra/restapi/v1/plugins/controller.py#L232-L240) saying argument 7 is an integer and not a boolean.

**Comment by jkglasbrenner** [comment]
TODO: In controller.py for plugins endpoint, switch the `file_id` parameter to `fileId`.

**Comment by pscemama-mitre** [comment]
Ready for review @jkglasbrenner @keithmanville

**Review by jkglasbrenner — APPROVED** [review]
LGTM

**Pull request merged**
