### PR TITLE
feat: Truncate long text

### PR DESCRIPTION
**Pull request by henrychoy**
This MR truncates long text for names, tags, and descriptions to better fit everything on the table pages.  If truncated, you can mouse-over to view a tooltip of the full text.  The cutoff for names and tags is 18 characters.  The cutoff for descriptions is 40 characters.

### CODE REVIEW

**Comment by etrapnell-nist** [comment]
This looks good except for one thing I noticed. If a name, description, or tag has only underscores and no spaces, the full text can get truncated on mouse-over. This is mainly a problem for plugin names, which can't contain spaces.

**Comment by henrychoy** [comment]
> This looks good except for one thing I noticed. If a name, description, or tag has only underscores and no spaces, the full text can get truncated on mouse-over. This is mainly a problem for plugin names, which can't contain spaces.

@etrapnell-nist Thanks, I just pushed a fix that wraps the text in the tooltip even if it has no spaces.  

@keithmanville I also noticed that the long text could still be an issue in many other places in the UI such as the page title, breadcrumbs, or buttons that have a dynamic label.  An easier way to tackle all those would be to enforce a character limit rule upon input, either on the frontend or backend.  If you want the frontend to handle it, let me know if you have any guidance on what the character limits for each type of resource should be.

**Comment by etrapnell-nist** [comment]
The only thing I see now is that experiment names still have the underscore wrap problem. Maybe because they are links? Looks good otherwise.

**Comment by henrychoy** [comment]
> The only thing I see now is that experiment names still have the underscore wrap problem. Maybe because they are links? Looks good otherwise.

Oops I missed that, yes the experiment name is handled separately since it's a link.  Just pushed up the fix now.

**Comment by etrapnell-nist** [comment]
Thanks! Looks good now.

**Review by etrapnell-nist — APPROVED** [review]

**Comment by keithmanville** [comment]
squashed and merged to dev

**Pull request closed without merging**
